# Generated by Django 5.0.4 on 2024-04-09 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('food_group', models.CharField(max_length=50)),
                ('meal_type', models.CharField(max_length=50)),
                ('serving', models.FloatField()),
                ('calorie', models.FloatField()),
                ('calorie_in', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
